server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation
    username: root
    password: happy05080!
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: application-security.yml


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.hibernate.SQL: debug

