spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/graduation
    username: sa
    password:
    driver-class-name: org.h2.Driver
  config:
    import: application-security.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug

